# Generated by Django 2.0.1 on 2018-01-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_urls', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('director', models.CharField(max_length=100)),
                ('actor', models.CharField(max_length=100)),
                ('userRating', models.CharField(max_length=10)),
            ],
        ),
    ]
