# Generated by Django 2.0.1 on 2018-01-10 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_movie_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Movie_info',
        ),
        migrations.AlterField(
            model_name='movie_search',
            name='keyword',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
