# Generated by Django 2.0.1 on 2018-01-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20180110_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
