# Generated by Django 2.0.1 on 2018-01-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20180110_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_search',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='movie_search',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product_search',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
