# Generated by Django 2.0.1 on 2018-01-11 07:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20180111_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_search',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
