# Generated by Django 2.0.1 on 2018-01-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20180111_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=5)),
                ('password', models.CharField(default='', max_length=40)),
                ('lastsearch', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='book_search',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='book_search',
            name='sex',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='movie_search',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='movie_search',
            name='sex',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='product_search',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product_search',
            name='sex',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
