# Generated by Django 2.0.1 on 2018-01-12 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20180111_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_search',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 1, 12, 23, 17, 42, 642399)),
        ),
    ]
